name: animated_appbar
description: AppBar which can dynamically change height with page navigation.
version: 2.1.3
homepage: https://flutterbased.studio
repository: https://github.com/namkyu1999/animated_appbar
issue_tracker: https://github.com/namkyu1999/animated_appbar/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  stack: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
